<?php
namespace TableSQL;

interface IOptions
{
	const LANGUAGE = 'LANGUAGE';
	const SITE = 'SITE01';
	const TABLE_OPTIONS_INSTALLED = 'TABLE_OPTIONS_INSTALLED';
	const TABLE_ORDERS_INSTALLED = 'TABLE_ORDERS_INSTALLED';
	const TABLE_PRODUCTS_INSTALLED = 'TABLE_PRODUCTS_INSTALLED';
	const TABLE_CATEGORY_INSTALLED = 'TABLE_CATEGORY_INSTALLED';
	const TABLE_INVOICE_INSTALLED = 'TABLE_INVOICE_INSTALLED';
	const TABLE_MAGAZINE_INSTALLED = 'TABLE_MAGAZINE_INSTALLED';
}

?>